### PR TITLE
First two scripts for review

### PR DESCRIPTION
**Pull request by andyb3**
Will also be adding a wrapper script that calls these, but would be good to get these two reviewed now

---
This change is [Reviewable](https://reviewable.io/reviews/moka-guys/100k_moka_variants/1)

### CODE REVIEW

**Review by aledj2 — COMMENTED** [review]
+@aledj2 

> *[Reviewable](https://reviewable.io/reviews/moka-guys/100k_moka_variants/1#-:-Lg7FlMb1el_EBoEIGkc:bweg3f8)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @aledj2, @NMNS93, and @woook)

**Review by aledj2 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/100k_moka_variants/1)* status: 0 of 3 files reviewed, 4 unresolved discussions (waiting on @andyb3, @NMNS93, and @woook)

___
*[100k_tier_1_2_vars.py, line 55 at r1](https://reviewable.io/reviews/moka-guys/100k_moka_variants/1#-Lg7TjBA7U7E6L0PBorO:-Lg7TjBP-qs6s86v66n1:bqolxu6) ([raw file](https://github.com/moka-guys/100k_moka_variants/blob/4fb4d06a6f495d0e5c9cdb49d268de9c3a574130/100k_tier_1_2_vars.py#L55)):*
> ```Python
>     for ig in interpreted_genomes_json:
>         # Convert the interpreted genome JSON into InterpretedGenome object from GeL Report Models v6.0
>         ig_obj = InterpretedGenome.fromJsonDict(ig['interpreted_genome_data'])
> ```

does this need a try/except? (question rather than a suggestion)
___
*[100k_tier_1_2_vars.py, line 64 at r1](https://reviewable.io/reviews/moka-guys/100k_moka_variants/1#-Lg7UGZt96Pu2tTHIfQY:-Lg7UGZt96Pu2tTHIfQZ:bctjqyp) ([raw file](https://github.com/moka-guys/100k_moka_variants/blob/4fb4d06a6f495d0e5c9cdb49d268de9c3a574130/100k_tier_1_2_vars.py#L64)):*
> ```Python
>             vars_by_cip[cip] = vars_by_cip.setdefault(cip, {})
>             # Add the variants for that cip/version to dictionary.
>             # If the same cip/version is already there (shouldn't ever happen but just a failsafe)
> ```

another question - do we want to know if this is the case?
___
*[100k_variant_validator.py, line 116 at r1](https://reviewable.io/reviews/moka-guys/100k_moka_variants/1#-Lg7_7YZCnSmWAjzU-96:-Lg7_7ZSDhIBbK4U6OiX:b-sj46p8) ([raw file](https://github.com/moka-guys/100k_moka_variants/blob/4fb4d06a6f495d0e5c9cdb49d268de9c3a574130/100k_variant_validator.py#L116)):*
> ```Python
>         # Some cases can't be lifted over, but check that there is at least a section for one of the two builds
>         if 'grch37' and 'grch38' not in var_json['primary_assembly_loci']:
>             sys.exit('No coordinates for GRCh37 or GRCh38')
> ```

no coordinates for GRch37 and GRCh38
___
*[README.md, line 8 at r1](https://reviewable.io/reviews/moka-guys/100k_moka_variants/1#-Lg7_tmk3FslCOP0ciU3:-Lg7_tmk3FslCOP0ciU4:b-mfpqa5) ([raw file](https://github.com/moka-guys/100k_moka_variants/blob/4fb4d06a6f495d0e5c9cdb49d268de9c3a574130/README.md#L8)):*
> ```Markdown
> The variant details are printed to stdout in a tab separated format with the following columns:
> 
> > Build&nbsp;&nbsp;&nbsp;&nbsp;Chromosome&nbsp;&nbsp;&nbsp;&nbsp;Position&nbsp;&nbsp;&nbsp;&nbsp;Ref&nbsp;&nbsp;&nbsp;&nbsp;Alt&nbsp;&nbsp;&nbsp;&nbsp;Genotype
> ```

is this deliberate or some weird html copy and pasting? (see also below x 3)

**Review by andyb3 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/100k_moka_variants/1)* status: 0 of 3 files reviewed, 4 unresolved discussions (waiting on @aledj2, @andyb3, @NMNS93, and @woook)

___
*[100k_tier_1_2_vars.py, line 55 at r1](https://reviewable.io/reviews/moka-guys/100k_moka_variants/1#-Lg7TjBA7U7E6L0PBorO:-Lg7b1x0Cr2p_d0KKmba:bz7ekmy) ([raw file](https://github.com/moka-guys/100k_moka_variants/blob/4fb4d06a6f495d0e5c9cdb49d268de9c3a574130/100k_tier_1_2_vars.py#L55)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

does this need a try/except? (question rather than a suggestion)
</blockquote></details>

I don't think so. If it fails I think it is fine (and desirable) for the whole script to fail. Going to catch error messages in the wrapper script that calls it.

**Review by aledj2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/100k_moka_variants/1)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @andyb3, @NMNS93, and @woook)

___
*[100k_tier_1_2_vars.py, line 55 at r1](https://reviewable.io/reviews/moka-guys/100k_moka_variants/1#-Lg7TjBA7U7E6L0PBorO:-Lg7g0g-EVyImNBVMcd9:b929pzm) ([raw file](https://github.com/moka-guys/100k_moka_variants/blob/4fb4d06a6f495d0e5c9cdb49d268de9c3a574130/100k_tier_1_2_vars.py#L55)):*
<details><summary><i>Previously, andyb3 wrote…</i></summary><blockquote>

I don't think so. If it fails I think it is fine (and desirable) for the whole script to fail. Going to catch error messages in the wrapper script that calls it.  
</blockquote></details>

agreed, just wanted to check it would fail!

**Review by andyb3 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/100k_moka_variants/1)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @aledj2, @NMNS93, and @woook)

___
*[100k_tier_1_2_vars.py, line 64 at r1](https://reviewable.io/reviews/moka-guys/100k_moka_variants/1#-Lg7UGZt96Pu2tTHIfQY:-Lg7t3sf8PNewPAu4UYM:bxor3i2) ([raw file](https://github.com/moka-guys/100k_moka_variants/blob/4fb4d06a6f495d0e5c9cdb49d268de9c3a574130/100k_tier_1_2_vars.py#L64)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

another question - do we want to know if this is the case?
</blockquote></details>

Yeah you're right current logic more appropriate for the negneg script (where this was copied from) where we just want to exclude anything that has variants.

I have re-written this function because I realised that this skips over all interpreted genomes that don't have any variants, whereas it should really keep them in
___
*[100k_variant_validator.py, line 116 at r1](https://reviewable.io/reviews/moka-guys/100k_moka_variants/1#-Lg7_7YZCnSmWAjzU-96:-Lg7tX7i0QH-CkftNIdi:b-896fix) ([raw file](https://github.com/moka-guys/100k_moka_variants/blob/4fb4d06a6f495d0e5c9cdb49d268de9c3a574130/100k_variant_validator.py#L116)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

no coordinates for GRch37 and GRCh38
</blockquote></details>

Done.
___
*[README.md, line 8 at r1](https://reviewable.io/reviews/moka-guys/100k_moka_variants/1#-Lg7_tmk3FslCOP0ciU3:-Lg7tXpV-udd_I5PlsFR:bi8zugx) ([raw file](https://github.com/moka-guys/100k_moka_variants/blob/4fb4d06a6f495d0e5c9cdb49d268de9c3a574130/README.md#L8)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

is this deliberate or some weird html copy and pasting? (see also below x 3)
</blockquote></details>

Deliberate, I couldn't find an easy way to insert tabs/spaces in markdown so ended up using html based on what I read [here](https://stackoverflow.com/questions/6046263/how-to-indent-a-few-lines-in-markdown-markup) but if you know another way I'd be happy to change!

**Review by aledj2 — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 3 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/100k_moka_variants/1#-:-Lg7wBot7_a1qD0LVuvP:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @NMNS93 and @woook)

**Pull request merged**
